sudo: required
services:
  - docker

before_install:
  - docker build -t vahramj/docker-react -f Dockerfile.dev .

scripts:
  #   - docker run vahramj/docker-react npm test -- --coverage
  - docker run -e CI=true vahramj/docker-react npm run test
