# sudo: required
# [travis understands docker? what is a service for travis exactly?]
services:
  - docker

before_install:
  - docker build -t vahramj/docker-react -f Dockerfile.dev .

script:
  #   - docker run vahramj/docker-react npm test -- --coverage
  - docker run -e CI=true vahramj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'simple-react-app-2'
  env: 'SimpleReactApp2-env'
  bucket_name: 'elasticbeanstalk-us-east-1-975710334054'
  bucket_path: 'simple-react-app-2'
  on:
    branch: development
  # secret_access_key:
  #   secure: "$AWS_SECRET_KEY"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
