sudo: required
services:
  - docker

before_install:
  - docker build -t vahramj/docker-react -f Dockerfile.dev .

scripts:
  #   - docker run vahramj/docker-react npm test -- --coverage
  - docker run -e CI=true vahramj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-975710334054'
  bucket_path: 'docker-react'
  on:
    branch: master
  # accesss_key_id: $AWS_ACCESS_KEY
  # secret_access_key:
  #   secure: $AWS_SECRET_KEY
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
